name: image2mano_params
channels:
  - menpo
  - defaults
  - conda-forge
dependencies:
  - opencv
  - python=3.7
  - matplotlib
  - numpy
  - pillow
  - trimesh
  - tqdm
  - git
  - pip
  - pip:
    - git+https://github.com/hassony2/chumpy.git
    - opencv-python
    - torch
    - torchvision
    - PyYAML
